In [ ]:
"""Tasks
1.
Create two NumPy arrays representing the daily step counts of two friends over
 a week and use element-wise addition, subtraction, multiplication, and division
   to compare their activity levels.
2.
Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices
 representing user-song interaction scores (user preferences and song popularity),
   use dot() and matmul() to compute the final recommendation matrix and explain 
   the difference between the two results.
3.
Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram
 image, use transpose (T) to rotate the image and then calculate the mean, median,
   standard deviation, and variance of the pixel values.
4.
Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid
 and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse,
   determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong>
     If the matrix is not invertible, modify one value and try again.</em>
5.
Create a NumPy array of shape (2, 6) representing the number of orders placed on 
Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into
 two equal parts, and then stack both parts vertically."""

In [1]:
"""1.
Create two NumPy arrays representing the daily step counts of two friends over
 a week and use element-wise addition, subtraction, multiplication, and division
   to compare their activity levels."""

import numpy as np

friend1 = np.array([1234,5621,3254,9635,8526,4552,8563])
friend2 = np.array([9635,3254,8526,1234,5621,485,7512])


addition = friend1 + friend2
subtraction = friend1 - friend2
multiplication = friend1 * friend2
division = friend1 / friend2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)



Addition: [10869  8875 11780 10869 14147  5037 16075]
Subtraction: [-8401  2367 -5272  8401  2905  4067  1051]
Multiplication: [11889590 18290734 27743604 11889590 47924646  2207720 64325256]
Division: [0.12807473 1.72741242 0.38165611 7.80794165 1.51681196 9.38556701
 1.13990948]


In [ ]:
"""
2.
Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices
 representing user-song interaction scores (user preferences and song popularity),
use dot() and matmul() to compute the final recommendation matrix and explain 
the difference between the two results.
   """

import numpy as np

# User preferences
preferences = np.array([
    [5, 2, 1],
    [1, 4, 2],
    [2, 1, 5]
])

# Song popularity
popularity = np.array([
    [4, 1, 2],
    [2, 5, 1],
    [1, 2, 4]
])

# Using dot()
dot_result = np.dot(preferences, popularity)

# Using matmul()
matmul_result = np.matmul(preferences, popularity)

print("Dot Result:")
print(dot_result)

print("\nMatmul Result:")
print(matmul_result)

"""                    `np.dot()`             |              `np.matmul()` |

 General-purpose dot product function         | Specifically designed for matrix 
                                                multiplication 
Can behave differently depending on           |
 array dimensions                             | Follows matrix multiplication rules |
| Works with vectors and matrices             |  Mainly used for matrix multiplication |
| For 2D matrices, it gives the same 
result as `matmul()`                          | For 2D matrices, it gives the
                                                same result as `dot()` """

Dot Result:
[[25 17 16]
 [14 25 14]
 [15 17 25]]

Matmul Result:
[[25 17 16]
 [14 25 14]
 [15 17 25]]


In [1]:
"""
3.
Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram
 image, use transpose (T) to rotate the image and then calculate the mean, median,
   standard deviation, and variance of the pixel values."""

import numpy as np

# 4x4 matrix representing pixel brightness
image = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# Transpose the matrix
rotated_image = image.T

print("Original Image:")
print(image)

print("\nTransposed Image:")
print(rotated_image)

# Calculate statistical values
mean = np.mean(image)
median = np.median(image)
std = np.std(image)
variance = np.var(image)

print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std)
print("Variance:", variance)

Original Image:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

Transposed Image:
[[ 10  50  90 130]
 [ 20  60 100 140]
 [ 30  70 110 150]
 [ 40  80 120 160]]

Mean: 85.0
Median: 85.0
Standard Deviation: 46.09772228646444
Variance: 2125.0


In [ ]:
"""4.
Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid
 and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse,
   determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong>
     If the matrix is not invertible, modify one value and try again.</em>
"""

import numpy as np

# 3x3 Zomato restaurant rating correlation matrix
rating = np.array([
    [5, 2, 1],
    [2, 4, 2],
    [1, 2, 3]
])

# Determinant
det = np.linalg.det(rating)

# Inverse
inverse = np.linalg.inv(rating)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(rating)

print("Matrix:")
print(rating)

print("\nDeterminant:")
print(det)

print("\nInverse:")
print(inverse)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrix:
[[5 2 1]
 [2 4 2]
 [1 2 3]]

Determinant:
32.0

Inverse:
[[ 0.25   -0.125   0.    ]
 [-0.125   0.4375 -0.25  ]
 [ 0.     -0.25    0.5   ]]

Eigenvalues:
[7.50466435+0.j 3.13535911+0.j 1.35997653+0.j]

Eigenvectors:
[[ 0.66260047+0.j  0.72851788+0.j  0.17384567+0.j]
 [ 0.61886638+0.j -0.4018081 +0.j -0.67494789+0.j]
 [ 0.42185901+0.j -0.55480803+0.j  0.71709346+0.j]]


In [6]:
"""
5.
Create a NumPy array of shape (2, 6) representing the number of orders placed on 
Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into
 two equal parts, and then stack both parts vertically."""

import numpy as np

# Orders placed in two cities over 6 days
orders = np.array([
    [120, 150, 180, 200, 170, 160],
    [100, 130, 140, 160, 150, 180]
])

print("Original Array:")
print(orders)

# Reshape from (2, 6) to (3, 4)
reshaped = orders.reshape(3, 4)
print("\nReshaped Array:")
print(reshaped)

# Flatten the array
flattened = reshaped.flatten()
print("\nFlattened Array:")
print(flattened)

# Split into two equal parts
part1, part2 = np.split(flattened, 2)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

# Stack both parts vertically
stacked = np.vstack((part1, part2))

print("\nVertically Stacked Array:")
print(stacked)

Original Array:
[[120 150 180 200 170 160]
 [100 130 140 160 150 180]]

Reshaped Array:
[[120 150 180 200]
 [170 160 100 130]
 [140 160 150 180]]

Flattened Array:
[120 150 180 200 170 160 100 130 140 160 150 180]

Part 1:
[120 150 180 200 170 160]

Part 2:
[100 130 140 160 150 180]

Vertically Stacked Array:
[[120 150 180 200 170 160]
 [100 130 140 160 150 180]]
