In [ ]:
"""Tasks
1.
Create a 2D NumPy array representing the ratings (out of 5) given by 4 users 
to 5 different food items on Zomato. Use slicing to extract the ratings given 
by the second and third users only.
2.
Given a NumPy array of daily steps tracked for 10 days, use boolean indexing 
to select only the days where the steps were greater than 8000.
<br><br><em><strong>Hint:</strong> Use an array like 
steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>
3.
Create a NumPy array of IPL team scores for 8 matches. 
Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.
4.
Suppose you have a NumPy array of product prices from Flipkart.
 Use broadcasting to apply a 10% discount to all prices and print the new array.
 <br><br><em><strong>Constraint:</strong> Do not use any loops.</em>
5.
Given a NumPy array of user ratings (can be negative, zero, or positive)
 for songs on Spotify, use boolean masking to set all negative ratings to zero, 
 keeping other ratings unchanged."""

In [ ]:
"""1.
Create a 2D NumPy array representing the ratings (out of 5) given by 4 users 
to 5 different food items on Zomato. Use slicing to extract the ratings given 
by the second and third users only."""

import numpy as np

rating = np.array([[2,4,3,5,2],
                   [4,2,3,1,5],
                   [3,5,1,2,4],
                   [1,3,2,4,5]])

print(rating)
print(rating[1:3])


[[2 4 3 5 2]
 [4 2 3 1 5]
 [3 5 1 2 4]
 [1 3 2 4 5]]
[[4 2 3 1 5]
 [3 5 1 2 4]]


In [ ]:
"""
2.
Given a NumPy array of daily steps tracked for 10 days, use boolean indexing 
to select only the days where the steps were greater than 8000.
<br><br><em><strong>Hint:</strong> Use an array like 
steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>"""

import numpy as np

steps = np.array([7500, 8200, 9000, 1523, 500, 8520 ,9546, 7896, 2304, 5612])

result = steps[steps > 8000]

print(result)


[8200 9000 8520 9546]


In [13]:
"""3.
Create a NumPy array of IPL team scores for 8 matches. 
Use fancy indexing to select the scores from matches 2, 5, and 7, and print them."""

import numpy as np

IPL_team = np.array([125,122,178,369, 564, 254, 234, 333 ])

result = IPL_team[[2,5,7]]

print(result)

[178 254 333]


In [3]:
"""
4.
Suppose you have a NumPy array of product prices from Flipkart.
 Use broadcasting to apply a 10% discount to all prices and print the new array.
 <br><br><em><strong>Constraint:</strong> Do not use any loops.</em>
 """
import numpy as np

product_prices = np.array([450,234,654,852,753,951])

discount = product_prices * 10 / 100

result = product_prices - discount

print(result)

[405.  210.6 588.6 766.8 677.7 855.9]


In [5]:
"""5.
Given a NumPy array of user ratings (can be negative, zero, or positive)
 for songs on Spotify, use boolean masking to set all negative ratings to zero, 
 keeping other ratings unchanged."""

import numpy as np 

ratings = np.array([5, -2, 3, -1, 0, 4, -3])

ratings[ratings < 0] = 0

print(ratings)



[5 0 3 0 0 4 0]
